l=input("enter the string")
print("Stripping the spaces")
l=l.strip(" ")
print(l)
print("Splitting the words")
l=l.split(" ")
print(l)
print("")
wo=input("Enter the word you want to see the count")
x=l.count(wo)
print("the count of the word is:" +str(x))
print("")
print("join back to string with ',' in middle")
l=",".join(str(i) for i in l)
print(l)
print("")
